### PR TITLE
Usgs/hazdev template#189

### PR DESCRIPTION
**Pull request by hasimpson-usgs**
fixes usgs/hazdev-template#189 

Review visual aesthetics of application that may have been impacted by recent template changes.

### CODE REVIEW

**Comment by hasimpson-usgs** [comment]
I don't like the way the chevrons look,  I figured I'd push it up for debate.

**Comment by ehunter-usgs** [comment]
- why not just open the example page, since there is only one? Remove example.php
 - headers have bottom margin, this breaks .accordion-toggle away from .accordion-content
  - just update, .accordion-toggle { margin: 1em 0 0; }
 - remove extra h1 on example page "Accordion Example"

**Comment by ehunter-usgs** [comment]
Test in IE

**Comment by ehunter-usgs** [comment]
replaced by https://github.com/usgs/hazdev-accordion/pull/11

**Pull request closed without merging**
